### PR TITLE
pos-tip-show: allow to specifie the font family

### PR DESCRIPTION
**Pull request by sebastiencs**
We can now select which font to use in the tooltip.
Example of use:
```el
(pos-tip-show "Some text" x x x x x x x x "Open Sans Light")
```

### CODE REVIEW

**Comment by pitkali** [comment]
Hi!

Thanks for getting in touch.

I must admit I'm not a fan of indexing into font-family vector with magic indices. I'm appalled that font-info documentation seems to pretty much require this. Yuck.

However, more importantly, if setting tooltip colours is not enough for you, why should you stop at font family? What about size?

I wonder if we could rework tip-color argument. It can be a face, but only colours are used. If you want to customise the font family, which probably does make sense in these modern times, you should probably allow for it to specify other font parameters as well, and default to frame font.

That wouldn't be backwards compatible, but one wonders how much of an issue that would be in this case. If you used to use a face to specify tooltip colours, would you be distraught if it started using font family and size from that face? Probably not.

Kind regards,
Piotr

**Comment by sebastiencs** [comment]
Hi @pitkali 

Well I didn't want to make big changes on the code, but I agree with your ideas: more could be done.

I think the best would be to let the user add properties to the string he gives to `pos-tip-show` (like with `pos-tip-show-no-propertize`) and use a face as default on the tooltip.

An image will explain it better:
pos-tip2

What do you think ?

**Comment by pitkali** [comment]
Sorry for late response. I had a rough week.

Why would user propertize the string given to pos-tip-show instead of using pos-tip-show-no-propertize, which seems to be specifically meant by the original author as the pos-top-show version that doesn't do that?

**Comment by pitkali** [comment]
It's been 2 months. Tentatively closing without merging as redundant, based on the comment above.

**Pull request closed without merging**
