### PR TITLE
Fix pos-tip-compute-*-color on nil tip-color

### PR DESCRIPTION
**Pull request by LiuPai**
`facep` on nil return an unspecified face

### CODE REVIEW

**Comment by pitkali** [comment]
This is weird. `nil` is not a face name, so should result in predicate check failing. It does for me, for that matter.

Where did you observe such behaviour? On what version of emacs?

By the way, unfortunately enough, I'm leaving for vacation in a few hours, so I will not be able to follow up on this until August 3rd.

**Comment by LiuPai** [comment]
Emacs from archlinux offical repo, and version is 
`GNU Emacs 24.5.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.20.6) of 2016-06-05 on juergen`
`(facep nil) => [face unspecified unspecified unspecified unspecified unspecified unspecified unspecified unspecified unspecified unspecified unspecified ...]`

**Comment by pitkali** [comment]
Can you reproduce it without local configuration, so when running `emacs -Q` ? I tried emacs 24.5 in my Linux virtual machine, and it behaved as expected (i.e., it returned `nil`).

This looks like a bug in arch patches, at the very least. I guess if that's the case it is easy enough to patch on our side. Still makes me angry that they would break perfectly sensible behaviour.

**Comment by LiuPai** [comment]
I tried with `emacs -q` and the `facep` works right now.

**Comment by LiuPai** [comment]
Sorry, seems my config file break `facep` behavior, this pull request can be close now.

**Pull request closed without merging**
